#!/usr/bin/env python

import urllib
import requests

from bs4 import BeautifulSoup

BASE = "https://catalogue.mcgill.ca/F/?func=login-session"

s = requests.Session()

r = s.get(BASE)

soup = BeautifulSoup(r.text, "html.parser")

POST_LINK = soup.find("form", class_="loginsession").attrs["action"]

with open("mcgill-lib-secret.txt", "r") as f:
    lines = f.read().splitlines()

USER = lines[0]
PASS = lines[1]

payload = {
        "ssl_flag":"Y",
        "func":"login-session",
        "bor_library":"MGU50",
        "login_source":"",
        "folder":"",
        "req_type":"",
        "bor_id":USER,
        "bor_verification":PASS,
        "func=login":"Sign in"
        }

header = {
        "Referer" : "https://catalogue.mcgill.ca/F/?func=login-session"
        }

r = s.post(POST_LINK, data=payload, headers=header)
loan_page = s.get(POST_LINK + "?func=bor-loan")
loan_soup = BeautifulSoup(loan_page.text, "html.parser")
RENEW_LINK = loan_soup.find("span", class_ = "buttons").find("a", title = "Renew All").attrs["href"].split("javascript:replacePage('")[1][:-3]

resp = s.get(RENEW_LINK)

if resp.text.find("Loan cannot be renewed") != -1:
    print("Could not renew a book.")
else:
    print("Success")
