#!/usr/bin/env python

import requests

from bs4 import BeautifulSoup

BASE = "https://catalogue.mcgill.ca/F/?func=login-session"

s = requests.Session()

r = s.get(BASE)

soup = BeautifulSoup(r.text, "html.parser")

POST_LINK = soup.find("form", class_="loginsession").attrs["action"]

with open("mcgill-lib-secret.txt", "r") as f:
    lines = f.readlines()

USER = lines[0]
PASS = lines[1]

payload = {
        "ssl_flag":"Y",
        "func":"login-session",
        "bor_library":"MGU50",
        "login_source":"",
        "folder":"",
        "req_type":"",
        "bor_id":USER,
        "bor_verification":PASS,
        "func=login":"Sign in"
        }

r = s.post(POST_LINK, data=payload)
